server:
  port: 8080
  mode: debug

database:
  driver: postgres  # or sqlite
  host: localhost
  port: 5432
  username: postgres
  password: password
  dbname: myapp
  sslmode: disable
  auto_migrate: true  # 마이그레이션 활성화/비활성화 설정

kafka:
  brokers:
    - localhost:9092  # 내부 통신용 포트 사용
  topic: myapp-topic 

auth:
  symmetric_key: "your-32-byte-secret-key-here-12345678"  # 32바이트 키
  token_duration: 24h 